/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiHelperRouteImport } from './routes/ai-helper'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as HomeworkRouteImport } from './routes/homework'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as AiHelperIndexRouteImport } from './routes/ai-helper.index'
import { Route as AiHelperThreadIdRouteImport } from './routes/ai-helper.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiOcrRouteImport } from './routes/api/ocr'
import { Route as ApiSuggestRouteImport } from './routes/api/suggest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHelperRoute = AiHelperRouteImport.update({
  id: '/ai-helper',
  path: '/ai-helper',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkRoute = HomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHelperIndexRoute = AiHelperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiHelperRoute,
} as any)
const AiHelperThreadIdRoute = AiHelperThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AiHelperRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOcrRoute = ApiOcrRouteImport.update({
  id: '/api/ocr',
  path: '/api/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestRoute = ApiSuggestRouteImport.update({
  id: '/api/suggest',
  path: '/api/suggest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-helper': typeof AiHelperRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/homework': typeof HomeworkRoute
  '/notes': typeof NotesRoute
  '/subjects': typeof SubjectsRoute
  '/ai-helper/$threadId': typeof AiHelperThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ocr': typeof ApiOcrRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/ai-helper/': typeof AiHelperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/homework': typeof HomeworkRoute
  '/notes': typeof NotesRoute
  '/subjects': typeof SubjectsRoute
  '/ai-helper/$threadId': typeof AiHelperThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ocr': typeof ApiOcrRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/ai-helper': typeof AiHelperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-helper': typeof AiHelperRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/homework': typeof HomeworkRoute
  '/notes': typeof NotesRoute
  '/subjects': typeof SubjectsRoute
  '/ai-helper/$threadId': typeof AiHelperThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ocr': typeof ApiOcrRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/ai-helper/': typeof AiHelperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-helper'
    | '/dashboard'
    | '/exams'
    | '/homework'
    | '/notes'
    | '/subjects'
    | '/ai-helper/$threadId'
    | '/api/chat'
    | '/api/ocr'
    | '/api/suggest'
    | '/ai-helper/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/exams'
    | '/homework'
    | '/notes'
    | '/subjects'
    | '/ai-helper/$threadId'
    | '/api/chat'
    | '/api/ocr'
    | '/api/suggest'
    | '/ai-helper'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-helper'
    | '/dashboard'
    | '/exams'
    | '/homework'
    | '/notes'
    | '/subjects'
    | '/ai-helper/$threadId'
    | '/api/chat'
    | '/api/ocr'
    | '/api/suggest'
    | '/ai-helper/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiHelperRoute: typeof AiHelperRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExamsRoute: typeof ExamsRoute
  HomeworkRoute: typeof HomeworkRoute
  NotesRoute: typeof NotesRoute
  SubjectsRoute: typeof SubjectsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiOcrRoute: typeof ApiOcrRoute
  ApiSuggestRoute: typeof ApiSuggestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-helper': {
      id: '/ai-helper'
      path: '/ai-helper'
      fullPath: '/ai-helper'
      preLoaderRoute: typeof AiHelperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework': {
      id: '/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof HomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-helper/': {
      id: '/ai-helper/'
      path: '/'
      fullPath: '/ai-helper/'
      preLoaderRoute: typeof AiHelperIndexRouteImport
      parentRoute: typeof AiHelperRoute
    }
    '/ai-helper/$threadId': {
      id: '/ai-helper/$threadId'
      path: '/$threadId'
      fullPath: '/ai-helper/$threadId'
      preLoaderRoute: typeof AiHelperThreadIdRouteImport
      parentRoute: typeof AiHelperRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ocr': {
      id: '/api/ocr'
      path: '/api/ocr'
      fullPath: '/api/ocr'
      preLoaderRoute: typeof ApiOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest': {
      id: '/api/suggest'
      path: '/api/suggest'
      fullPath: '/api/suggest'
      preLoaderRoute: typeof ApiSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AiHelperRouteChildren {
  AiHelperThreadIdRoute: typeof AiHelperThreadIdRoute
  AiHelperIndexRoute: typeof AiHelperIndexRoute
}

const AiHelperRouteChildren: AiHelperRouteChildren = {
  AiHelperThreadIdRoute: AiHelperThreadIdRoute,
  AiHelperIndexRoute: AiHelperIndexRoute,
}

const AiHelperRouteWithChildren = AiHelperRoute._addFileChildren(
  AiHelperRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiHelperRoute: AiHelperRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExamsRoute: ExamsRoute,
  HomeworkRoute: HomeworkRoute,
  NotesRoute: NotesRoute,
  SubjectsRoute: SubjectsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiOcrRoute: ApiOcrRoute,
  ApiSuggestRoute: ApiSuggestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
